import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rjiksmuseum shuffle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className="flex flex-col items-center">
        <div>
          <h1 className="text-2xl mt-4 mb-8">Rijksmuseum shuffle</h1>
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
